# Generated by Django 4.1.7 on 2023-02-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="period_of_execution",
            field=models.DateTimeField(),
        ),
    ]
